# Generated by Django 4.1.7 on 2023-04-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_diary', '0002_alter_destination_options_destination_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destination_images/'),
        ),
        migrations.AlterField(
            model_name='travelentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_entry_images/'),
        ),
    ]
